### PR TITLE
tweak(server/onesync): optimized table insert

### PR DESCRIPTION
**Pull request by Olvidate**
better way to insert tables

### CODE REVIEW

**Comment by benzon** [comment]
I think you need to explain why is this better?

Have you benchmarked table.insert via your method?

**Comment by benzon** [comment]
Okay used some time to do the a messy benchmark.

Your method looks to be faster, actually quite a bit about 50% faster then table.insert, quite supriced to be honest.

local testTable = {}
local testTableTwo = {}

```
nClock = os.clock()
for i=1,999999 do
    testTable[#testTable + 1] = 'test'
end
print(os.clock()-nClock)

nClock = os.clock()
for i=1,999999 do
    table.insert(testTableTwo, 'test')
end
print(os.clock()-nClock)
```

**Comment by thelindat** [comment]
Didn't realise I had table.insert here.

@benzon For benchmarking, fyi, you can use `os.nanotime` with LuaGLM (5.4).

```lua
local testTable = {}
local testTableTwo = {}

nClock = os.nanotime()
for i=1,1000000 do
    testTable[#testTable + 1] = 'test'
end
print((os.nanotime()-nClock) / 1000000) -- 27.5246

nClock = os.nanotime()
for i=1,1000000 do
    table.insert(testTableTwo, 'test')
end
print((os.nanotime()-nClock) / 1000000) -- 56.9259

local table_insert = table.insert

nClock = os.nanotime()
for i=1,1000000 do
    table_insert(testTableTwo, 'test')
end
print((os.nanotime()-nClock) / 1000000) -- 45.3891
```

**Comment by thelindat** [comment]
Looping over 200 players to retrieve {id, ped, coords} takes ~0.3316ms

```lua
local GetPlayerPed = GetPlayerPed
local GetEntityCoords = GetEntityCoords
```
Brings the time to ~0.2821ms, and storing the count (instead of using length operator) ~0.2753ms

Using those locals and adding `local table_insert = table.insert` instead takes ~0.3213ms

**Pull request merged**
